### ISSUE TITLE
Bitcoin payment discount feature

### ISSUE THREAD

**Issue by samuelbohler** [bitpay/bitpay-plugin#1]
Most shopping carts have a discount/promotion feature and can have it conditional upon the payment method used.

We encourage the marketing strategy of providing discounts for Bitcoin users due to the lower transaction costs, but leave it up to the merchants to figure out how to set them up.

A possible new feature would be to add a field to enter a percentage discount (or other type of discount) tied to the payment method, so that merchants could just enter the amount of the discount and have it setup and enabled upon saving their configuration.

**Comment by ionux** [comment]
Yep, good thinking, Sam!  We would need to ensure this wouldn't conflict with some shopping carts that offer the same functionality.

**Comment by samuelbohler** [comment]
Credit goes to one of our merchants who suggested it.  For shopping carts that offer the functionality, the feature could simply hook into that extant functionality and simply act as a shortcut of sorts.
